services:
  app:
    container_name: home
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: "base64:SAbeCFsMTheXHesmaiB9rrfSx1RjWqw5x86Zxwx12Wc="
      APP_URL: http://172.22.22.174

      DB_CONNECTION: mysql
      DB_HOST: 172.22.22.172
      DB_PORT: 3306
      DB_DATABASE: home
      DB_USERNAME: root
      DB_PASSWORD: "admb4r4t40**"

      ORACLE_DB_CONNECTION: oracle
      ORACLE_DB_HOST: 172.22.0.176
      ORACLE_DB_PORT: 1521
      ORACLE_DB_SERVICE_NAME: wint
      ORACLE_DB_USERNAME: baratao
      ORACLE_DB_PASSWORD: senha
